on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: repok8s.azurecr.io
        username: ${{ secrets.acr_repok8s_username }}
        password: ${{ secrets.acr_repok8s_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t repok8s.azurecr.io/k8sregion1:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push repok8s.azurecr.io/k8sregion1:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_k8sregion1_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep k8s-region1 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace k8s-region1`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: k8s-region1
        container-registry-url: repok8s.azurecr.io
        container-registry-username: ${{ secrets.acr_repok8s_username }}
        container-registry-password: ${{ secrets.acr_repok8s_password }}
        secret-name: k8sregion1dockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: k8s-region1
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
        images: |
          repok8s.azurecr.io/k8sregion1:${{ github.sha }}
        imagepullsecrets: |
          k8sregion1dockerauth
